#!/bin/bash

FILES="src/assert.sql
src/functions/*.sql
src/assertions/*.sql
src/grants.sql"

dest="framework/assert.sql"


echo "-- The PL/pgSQL Unit Testing framework
-- Do not edit this file manually!" > $dest

for file in $FILES
do
    echo "
    /* $file */
    " >> $dest

    cat $file >> $dest
done


echo "
The PL/pgSQL Unit Testing framework

    Install: 
        psql -U user -d database < $dest

    And make your tests ;)

    Tips:
        The view 'assert.view_tests' provides access to useful information about each test in the Postgres-CI database.
        Use a function assert.add_test('schema', 'test') to register your test in Postgres-CI database or an assert.remove_test(test_id) for remove it.
        Use a function assert.test_runner() to run your tests.
"