#!/bin/bash

FILES="src/assert.sql
src/functions/*.sql
src/assertions/*.sql
src/grants.sql"

dest="framework/assert.sql"


echo "-- The PLpgSQL Unit Testing framework
-- Do not edit this file manually!" > $dest

for file in $FILES
do
	echo "
    /* $file */
	" >> $dest

	cat $file >> $dest
done
